// GENERATED by scripts/art/build.mjs — do not edit by hand. Run `pnpm art`.
//
// The visual bible of Etapa IV: every sprite is an indexed PNG under public/art. Animations are
// horizontal sheets, so `width` is one frame and the file is `width * frames` wide.

export interface ArtAsset {
  /** Absolute path served from public/. */
  readonly src: string;
  /** Width of a single frame, in sprite pixels. */
  readonly width: number;
  /** Height of a single frame, in sprite pixels. */
  readonly height: number;
  /** 1 for a still sprite, >1 for an animation sheet. */
  readonly frames: number;
}

export const ART = {
  mark: { src: '/art/mark.png', width: 24, height: 24, frames: 1 },
  'avatar-forma-1': { src: '/art/avatar-forma-1.png', width: 32, height: 48, frames: 1 },
  'avatar-forma-2': { src: '/art/avatar-forma-2.png', width: 32, height: 48, frames: 1 },
  'avatar-forma-3': { src: '/art/avatar-forma-3.png', width: 32, height: 48, frames: 1 },
  'avatar-forma-4': { src: '/art/avatar-forma-4.png', width: 32, height: 48, frames: 1 },
  'leader-cantera': { src: '/art/leader-cantera.png', width: 32, height: 48, frames: 1 },
  'leader-yunque': { src: '/art/leader-yunque.png', width: 32, height: 48, frames: 1 },
  'leader-resorte': { src: '/art/leader-resorte.png', width: 32, height: 48, frames: 1 },
  'leader-vertigo': { src: '/art/leader-vertigo.png', width: 32, height: 48, frames: 1 },
  'medal-cantera-locked': {
    src: '/art/medal-cantera-locked.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-cantera-progress': {
    src: '/art/medal-cantera-progress.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-cantera-earned': {
    src: '/art/medal-cantera-earned.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-yunque-locked': { src: '/art/medal-yunque-locked.png', width: 24, height: 24, frames: 1 },
  'medal-yunque-progress': {
    src: '/art/medal-yunque-progress.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-yunque-earned': { src: '/art/medal-yunque-earned.png', width: 24, height: 24, frames: 1 },
  'medal-resorte-locked': {
    src: '/art/medal-resorte-locked.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-resorte-progress': {
    src: '/art/medal-resorte-progress.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-resorte-earned': {
    src: '/art/medal-resorte-earned.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-vertigo-locked': {
    src: '/art/medal-vertigo-locked.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-vertigo-progress': {
    src: '/art/medal-vertigo-progress.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'medal-vertigo-earned': {
    src: '/art/medal-vertigo-earned.png',
    width: 24,
    height: 24,
    frames: 1,
  },
  'type-masa': { src: '/art/type-masa.png', width: 16, height: 16, frames: 1 },
  'type-fuerza': { src: '/art/type-fuerza.png', width: 16, height: 16, frames: 1 },
  'type-motor': { src: '/art/type-motor.png', width: 16, height: 16, frames: 1 },
  'type-control': { src: '/art/type-control.png', width: 16, height: 16, frames: 1 },
  'type-aventura': { src: '/art/type-aventura.png', width: 16, height: 16, frames: 1 },
  'type-regen': { src: '/art/type-regen.png', width: 16, height: 16, frames: 1 },
  'object-creatina': { src: '/art/object-creatina.png', width: 16, height: 16, frames: 1 },
  'object-whey': { src: '/art/object-whey.png', width: 16, height: 16, frames: 1 },
  'object-cafeina': { src: '/art/object-cafeina.png', width: 16, height: 16, frames: 1 },
  'object-electrolitos': { src: '/art/object-electrolitos.png', width: 16, height: 16, frames: 1 },
  'object-b12': { src: '/art/object-b12.png', width: 16, height: 16, frames: 1 },
  'object-d-omega3': { src: '/art/object-d-omega3.png', width: 16, height: 16, frames: 1 },
  'object-sauna': { src: '/art/object-sauna.png', width: 16, height: 16, frames: 1 },
  'object-frio': { src: '/art/object-frio.png', width: 16, height: 16, frames: 1 },
  'object-siesta': { src: '/art/object-siesta.png', width: 16, height: 16, frames: 1 },
  'object-paseo': { src: '/art/object-paseo.png', width: 16, height: 16, frames: 1 },
  'object-batido': { src: '/art/object-batido.png', width: 16, height: 16, frames: 1 },
  'scene-ruta': { src: '/art/scene-ruta.png', width: 160, height: 48, frames: 1 },
  'scene-zona-salvaje': { src: '/art/scene-zona-salvaje.png', width: 160, height: 48, frames: 1 },
  'anim-gate': { src: '/art/anim-gate.png', width: 64, height: 48, frames: 8 },
  'anim-medal-burst': { src: '/art/anim-medal-burst.png', width: 32, height: 32, frames: 8 },
  'anim-evolution': { src: '/art/anim-evolution.png', width: 32, height: 48, frames: 8 },
  'anim-pv-ok': { src: '/art/anim-pv-ok.png', width: 16, height: 16, frames: 4 },
  'anim-pv-cargado': { src: '/art/anim-pv-cargado.png', width: 16, height: 16, frames: 4 },
  'anim-pv-ko': { src: '/art/anim-pv-ko.png', width: 16, height: 16, frames: 4 },
} as const satisfies Record<string, ArtAsset>;

export type ArtId = keyof typeof ART;
